import type { ClientContext } from '@deepseek-ai/dsh-client-runtime/client'

const STYLE_ID = 'dsh-skin-runtime/styles'

/** Runtime-owned CSS that uses official tokens and stable slot markers only. */
export const SKIN_RUNTIME_CSS = `
body[data-dsh-skin]{--dsp-skin-page-base:#0d1114;--dsp-skin-shadow-soft:rgb(0 0 8 / 20%);--dsp-skin-shadow-medium:rgb(0 0 10 / 30%);--dsp-skin-shadow-strong:rgb(0 0 12 / 58%);--dsp-custom-background-shade-rgb:0 0 0;background-color:var(--dsp-skin-page-base);background-image:linear-gradient(115deg,color-mix(in srgb,var(--dsp-skin-accent) 11%,transparent),transparent 38%),var(--dsp-skin-background-image);background-position:center,var(--dsp-skin-background-position);background-size:cover;background-attachment:fixed;font-family:var(--dsp-skin-font-family);transition:background-color .35s ease,color .25s ease}
body[data-dsh-skin][data-dsh-skin-color-scheme="fixed-light"],body[data-dsh-skin][data-dsh-skin-color-scheme="adaptive"]:not([data-ds-dark-theme]){--dsp-skin-page-base:#eef9f8;--dsp-skin-shadow-soft:rgb(43 90 89 / 12%);--dsp-skin-shadow-medium:rgb(43 90 89 / 17%);--dsp-skin-shadow-strong:rgb(43 90 89 / 22%);--dsp-custom-background-shade-rgb:255 253 248}
body[data-dsh-skin] #root{background:transparent}
body[data-dsh-skin] [role="dialog"]{border:1px solid color-mix(in srgb,var(--dsp-skin-accent) 22%,var(--dsw-alias-border-l1));background:color-mix(in srgb,var(--dsw-alias-bg-overlay) 94%,transparent);box-shadow:var(--dsw-shadow-lv2,0 28px 80px var(--dsp-skin-shadow-strong)),inset 0 1px rgb(255 255 255 / 4%);backdrop-filter:blur(24px)}
body[data-dsh-skin] [role="dialog"] nav button[aria-current="true"]{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 72%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 22%,var(--dsw-alias-bg-layer-2));color:var(--dsw-alias-label-primary);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary) 10%,transparent),0 0 24px color-mix(in srgb,var(--dsp-skin-glow) 13%,transparent)}
body[data-dsh-skin] [role="dialog"] button[aria-haspopup="menu"]{border-color:transparent;background:transparent;color:var(--dsw-alias-label-primary);box-shadow:none}
body[data-dsh-skin] [role="dialog"] button[aria-haspopup="menu"]:hover,body[data-dsh-skin] [role="dialog"] button[aria-haspopup="menu"][aria-expanded="true"]{border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 38%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 8%,transparent);color:var(--dsw-alias-brand-text)}
body[data-dsh-skin] [role="dialog"] button[aria-pressed="true"]{border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 76%,var(--dsw-alias-border-l3));background:color-mix(in srgb,var(--dsw-alias-brand-primary) 10%,var(--dsw-alias-bg-layer-2));color:var(--dsw-alias-label-primary);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary) 11%,transparent),0 0 24px color-mix(in srgb,var(--dsp-skin-glow) 10%,transparent)}
body[data-dsh-skin] [role="dialog"] button[aria-pressed="true"]:not(:disabled){position:relative;background:color-mix(in srgb,var(--dsw-alias-brand-primary) 6%,var(--dsw-alias-bg-layer-2))}
body[data-dsh-skin] [role="dialog"] button[aria-pressed="true"]:not(:disabled):after{content:"✓";position:absolute;top:9px;right:10px;display:grid;place-items:center;width:17px;height:17px;border-radius:50%;background:var(--dsw-alias-brand-primary);color:#fff;font:700 11px/1 var(--dsp-skin-font-family);box-shadow:0 0 14px color-mix(in srgb,var(--dsp-skin-glow) 34%,transparent)}
body[data-dsh-skin] div[aria-selected="true"]{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 58%,var(--dsw-alias-border-l2));background:color-mix(in srgb,var(--dsw-alias-brand-primary) 10%,var(--dsw-specific-sidebar-nav-item-active));box-shadow:inset 0 0 20px color-mix(in srgb,var(--dsp-skin-glow) 6%,transparent)}
body[data-dsh-skin] [data-slot="sidebar.brand.name"]>span:last-child:not(:first-child){background:color-mix(in srgb,var(--dsp-skin-accent) 28%,var(--dsw-alias-bg-layer-3));color:var(--dsw-alias-label-primary)}
body[data-dsh-skin] [data-context-injection-body]{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 34%,var(--dsw-alias-border-l1));border-radius:7px;background:color-mix(in srgb,var(--dsw-specific-menu) 96%,transparent);box-shadow:inset 0 1px rgb(255 255 255 / 3%),0 12px 30px var(--dsp-skin-shadow-soft);color:var(--dsw-alias-label-secondary)}
body[data-dsh-skin] [data-context-injection-body] :is(dt,strong){color:var(--dsw-alias-label-primary)}
body[data-dsh-skin] [data-context-injection-body] :is(code,dd){color:var(--dsw-alias-brand-text)}
body[data-dsh-skin] [data-role-kind]{border:1px solid color-mix(in srgb,currentColor 28%,transparent);box-shadow:inset 0 1px rgb(255 255 255 / 4%);font-weight:750;letter-spacing:.025em}
body[data-dsh-skin] [data-role-kind="system"]{background:color-mix(in srgb,var(--dsp-skin-accent) 12%,var(--dsw-alias-bg-layer-3));color:color-mix(in srgb,var(--dsp-skin-accent) 76%,var(--dsw-alias-label-primary))}
body[data-dsh-skin] [data-role-kind="context"]{background:color-mix(in srgb,var(--dsw-alias-brand-primary) 17%,var(--dsw-alias-bg-layer-3));color:var(--dsw-alias-brand-text)}
body[data-dsh-skin] [data-role-kind="user"]{background:color-mix(in srgb,var(--dsp-skin-glow) 18%,var(--dsw-alias-bg-layer-3));color:color-mix(in srgb,var(--dsp-skin-glow) 58%,var(--dsw-alias-label-primary))}
body[data-dsh-skin] [data-slot="conversation.chat.node"] :not(pre)>code{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 30%,var(--dsw-alias-border-l1));border-radius:5px;padding:.1em .36em;background:color-mix(in srgb,var(--dsw-alias-brand-primary) 12%,var(--dsw-specific-menu));color:color-mix(in srgb,var(--dsw-alias-brand-text) 82%,var(--dsw-alias-label-primary));box-shadow:inset 0 1px rgb(255 255 255 / 4%);font-family:"Cascadia Code","SFMono-Regular",Consolas,monospace}
body[data-dsh-skin] [data-slot="conversation.chat.node"] pre{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 34%,var(--dsw-alias-border-l1));border-radius:12px;background:color-mix(in srgb,var(--dsw-specific-menu) 96%,transparent);color:var(--dsw-alias-label-primary);box-shadow:inset 0 1px rgb(255 255 255 / 4%),0 14px 34px var(--dsp-skin-shadow-medium)}
body[data-dsh-skin] [data-slot="conversation.chat.node"] pre code{border:0;padding:0;background:transparent;color:inherit;box-shadow:none}
body[data-dsh-skin] [data-slot="tool.call.toolview"] [data-expandable="true"][aria-expanded="true"]{border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 36%,var(--dsw-alias-border-l1));background:color-mix(in srgb,var(--dsw-alias-brand-primary) 7%,var(--dsw-specific-menu));color:var(--dsw-alias-label-primary)}
body[data-dsh-skin] #trajectory-detail-panel :is(p,li)>code{border:1px solid color-mix(in srgb,var(--dsp-skin-accent) 26%,var(--dsw-alias-border-l1));border-radius:5px;padding:.12em .38em;background:color-mix(in srgb,var(--dsw-alias-brand-primary) 13%,var(--dsw-specific-menu));color:var(--dsw-alias-brand-text);box-shadow:inset 0 1px rgb(255 255 255 / 4%)}
body[data-dsh-skin] [role="dialog"] button[aria-pressed="true"][disabled]>span:first-child>span:last-child{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 56%,var(--dsw-alias-border-l2));background:color-mix(in srgb,var(--dsw-alias-brand-primary) 24%,var(--dsw-alias-bg-layer-3));color:color-mix(in srgb,var(--dsw-alias-brand-text) 78%,var(--dsw-alias-label-primary));box-shadow:inset 0 1px rgb(255 255 255 / 5%)}
body[data-dsh-skin] [data-composer-card]{border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 68%,var(--dsw-alias-border-l2));background:color-mix(in srgb,var(--dsw-specific-input-major) 96%,transparent);box-shadow:var(--dsw-shadow-lv2,0 18px 52px var(--dsp-skin-shadow-strong)),0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary) 12%,transparent),0 0 30px color-mix(in srgb,var(--dsp-skin-glow) 11%,transparent);transition:border-color .16s ease,box-shadow .16s ease}
body[data-dsh-skin] [data-composer-card]:focus-within{border-color:var(--dsw-alias-brand-primary);box-shadow:var(--dsw-shadow-lv2,0 20px 58px var(--dsp-skin-shadow-strong)),0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary) 22%,transparent),0 0 34px color-mix(in srgb,var(--dsp-skin-glow) 16%,transparent)}
body[data-dsh-skin] [role="menu"]{border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 34%,var(--dsw-alias-border-l2));background:color-mix(in srgb,var(--dsw-specific-menu) 98%,transparent);box-shadow:var(--dsw-shadow-lv2,0 20px 56px var(--dsp-skin-shadow-strong)),0 0 0 1px color-mix(in srgb,var(--dsw-alias-brand-primary) 8%,transparent);backdrop-filter:blur(18px)}
body[data-dsh-skin] [role="menu"] [role="menuitem"]{border:1px solid transparent;color:var(--dsw-alias-label-secondary)}
body[data-dsh-skin] [role="menu"] [role="menuitem"]:is(:hover,:focus-visible){border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 24%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 9%,transparent);color:var(--dsw-alias-label-primary)}
body[data-dsh-skin] [role="menu"] button[role="menuitem"]:has(>svg){border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 34%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary) 13%,transparent);color:var(--dsw-alias-brand-text)}
body[data-dsh-skin] [role="menu"] button[role="menuitem"]:has(>svg)>svg{color:var(--dsw-alias-brand-primary)}
body[data-dsh-skin] [data-chat-flow-kind="turn-error"] [role="status"]>code{display:inline-flex;align-items:center;gap:7px;padding:7px 12px;border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 48%,transparent);border-radius:12px;background:color-mix(in srgb,var(--dsw-alias-brand-primary) 10%,var(--dsw-specific-menu));color:var(--dsw-alias-brand-text);font:700 12px/1.2 var(--ds-font-family-code,"Cascadia Code","SFMono-Regular",Consolas,monospace);letter-spacing:.035em;box-shadow:inset 0 1px rgb(255 255 255 / 4%),0 10px 26px var(--dsp-skin-shadow-soft)}
body[data-dsh-skin] [data-chat-flow-kind="turn-error"] [role="status"]>code:before{content:"!";display:grid;place-items:center;width:16px;height:16px;border-radius:50%;background:var(--dsw-alias-brand-primary);color:#fff;font:800 11px/1 var(--dsw-font-family,sans-serif)}
body[data-dsh-custom-background="true"]{position:relative;isolation:isolate}
body[data-dsh-custom-background="true"]:before,body[data-dsh-custom-background="true"]:after{content:"";position:fixed;pointer-events:none}
body[data-dsh-custom-background="true"]:before{z-index:-2;inset:-30px;background-image:var(--dsp-custom-background-image);background-position:var(--dsp-custom-background-position);background-size:var(--dsp-custom-background-size);background-repeat:no-repeat;background-color:var(--dsp-skin-page-base);filter:blur(var(--dsp-custom-background-blur));opacity:var(--dsp-custom-background-opacity);transition:opacity .24s ease,filter .24s ease}
body[data-dsh-custom-background="true"]:after{z-index:-1;inset:0;background:rgb(var(--dsp-custom-background-shade-rgb) / var(--dsp-custom-background-shade));transition:background-color .24s ease}
body[data-dsh-custom-background="true"] #root{background:transparent}
.dsp-settings{display:grid;gap:18px;max-width:980px;color:var(--dsw-alias-label-primary)}
.dsp-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:end;padding:28px;border:1px solid color-mix(in srgb,var(--dsw-alias-border-l2) 80%,var(--dsw-alias-brand-primary));border-radius:4px 22px 4px 22px;background:linear-gradient(120deg,color-mix(in srgb,var(--dsw-alias-bg-layer-1) 94%,var(--dsw-alias-brand-primary) 6%),var(--dsw-alias-bg-layer-1));box-shadow:0 18px 50px var(--dsp-skin-shadow-medium)}
.dsp-hero:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(135deg,transparent 0 18px,color-mix(in srgb,var(--dsw-alias-brand-primary) 6%,transparent) 18px 19px);pointer-events:none}
.dsp-kicker{position:relative;margin:0 0 8px;font-size:11px;font-weight:800;letter-spacing:.18em;color:var(--dsw-alias-brand-primary)}
.dsp-title{position:relative;margin:0;font-family:"Baskerville","Iowan Old Style",Georgia,serif;font-size:32px;font-weight:600;letter-spacing:-.025em}
.dsp-intro{position:relative;max-width:650px;margin:9px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:1.65}
.dsp-count{position:relative;display:grid;place-items:center;min-width:76px;min-height:76px;border:1px solid var(--dsw-alias-border-l2);border-radius:50%;background:var(--dsw-alias-bg-layer-2);font-variant-numeric:tabular-nums}.dsp-count strong{font-family:"Baskerville",Georgia,serif;font-size:25px}.dsp-count span{font-size:10px;letter-spacing:.12em;color:var(--dsw-alias-label-secondary)}
.dsp-toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 2px;border-bottom:1px solid var(--dsw-alias-border-l1)}
.dsp-status{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--dsw-alias-label-secondary)}.dsp-status i{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-state-success-primary);box-shadow:0 0 0 4px color-mix(in srgb,var(--dsw-alias-state-success-primary) 12%,transparent)}
.dsp-switch{display:flex;align-items:center;gap:9px;font-size:12px;font-weight:650;cursor:pointer}.dsp-switch input{appearance:none;width:34px;height:19px;margin:0;border:1px solid var(--dsw-alias-border-l2);border-radius:20px;background:var(--dsw-alias-bg-layer-2);transition:.18s ease}.dsp-switch input:after{content:"";display:block;width:13px;height:13px;margin:2px;border-radius:50%;background:var(--dsw-alias-label-secondary);transition:.18s ease}.dsp-switch input:checked{background:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}.dsp-switch input:checked:after{transform:translateX(15px);background:#fff}
.dsp-alert{padding:12px 14px;border-left:3px solid var(--dsw-alias-state-error-primary);background:color-mix(in srgb,var(--dsw-alias-state-error-primary) 9%,var(--dsw-alias-bg-layer-1));color:var(--dsw-alias-state-error-primary);font-size:13px}
.dsp-background{overflow:hidden;display:grid;grid-template-columns:minmax(260px,34%) minmax(0,1fr);min-height:238px;border:1px solid var(--dsw-alias-border-l1);border-radius:22px 5px 22px 5px;background:var(--dsw-alias-bg-layer-1);box-shadow:0 13px 38px var(--dsp-skin-shadow-soft)}
.dsp-background-preview{position:relative;overflow:hidden;min-height:238px;background:linear-gradient(145deg,#111921,#080b0e)}.dsp-background-preview:after{content:"";position:absolute;inset:0;border-right:1px solid color-mix(in srgb,var(--dsw-alias-border-l2) 72%,transparent);box-shadow:inset -22px 0 42px var(--dsp-skin-shadow-medium);pointer-events:none}.dsp-background-preview img{display:block;width:100%;height:100%;min-height:238px;position:absolute;inset:0;transition:filter .2s ease,opacity .2s ease,object-position .2s ease}.dsp-preview-shade{position:absolute;z-index:1;inset:0;background:rgb(var(--dsp-custom-background-shade-rgb));pointer-events:none}.dsp-local-badge{position:absolute;z-index:3;top:14px;left:14px;padding:5px 8px;border:1px solid rgb(255 255 255 / 18%);border-radius:20px;background:rgb(5 8 11 / 64%);backdrop-filter:blur(10px);color:#fff;font-size:9px;font-weight:800;letter-spacing:.15em}
.dsp-background-empty{position:absolute;inset:0;display:grid;place-items:center;background:radial-gradient(circle at center,color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent),transparent 32%),repeating-radial-gradient(circle at center,transparent 0 27px,rgb(255 255 255 / 5%) 28px 29px)}.dsp-background-empty i{position:absolute;width:104px;height:104px;border:1px dashed rgb(255 255 255 / 22%);border-radius:50%;transform:rotate(18deg)}.dsp-background-empty i:before,.dsp-background-empty i:after{content:"";position:absolute;inset:13px;border:1px solid rgb(255 255 255 / 10%);border-radius:50%}.dsp-background-empty i:after{inset:42px;background:var(--dsw-alias-brand-primary);border:0;box-shadow:0 0 30px color-mix(in srgb,var(--dsw-alias-brand-primary) 45%,transparent)}.dsp-background-empty span{position:relative;color:#fff;font-family:"Baskerville",Georgia,serif;font-size:13px;font-weight:800;letter-spacing:.16em}
.dsp-background-body{display:flex;min-width:0;flex-direction:column;padding:22px 24px}.dsp-background-heading{display:flex;align-items:center;justify-content:space-between;gap:18px}.dsp-background-heading p{margin:0 0 4px;color:var(--dsw-alias-brand-primary);font-size:9px;font-weight:800;letter-spacing:.16em}.dsp-background-heading h3{margin:0;font-family:"Baskerville","Iowan Old Style",Georgia,serif;font-size:22px;font-weight:650}.dsp-background-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:7px}.dsp-background-actions button,.dsp-control-fit button{border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:8px 11px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit;font-size:11px;font-weight:750;cursor:pointer;transition:.16s ease}.dsp-background-actions button:hover:not(:disabled),.dsp-control-fit button:hover{border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}.dsp-background-actions .dsp-button-quiet{background:transparent;color:var(--dsw-alias-label-secondary)}.dsp-background-actions button:disabled{opacity:.5;cursor:wait}.dsp-background-note{margin:9px 0 0;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:1.55}
.dsp-background-controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 18px;margin-top:auto;padding-top:18px}.dsp-background-toggle{grid-column:1/-1;justify-self:start}.dsp-control{display:grid;gap:7px;min-width:0}.dsp-control>span{display:flex;justify-content:space-between;color:var(--dsw-alias-label-secondary);font-size:10px;font-weight:750;letter-spacing:.04em}.dsp-control>span b{color:var(--dsw-alias-label-primary);font-weight:700;font-variant-numeric:tabular-nums}.dsp-control-fit>div{display:grid;grid-template-columns:1fr 1fr;padding:2px;border:1px solid var(--dsw-alias-border-l1);border-radius:9px;background:var(--dsw-alias-bg-base)}.dsp-control-fit button{border:0;background:transparent;padding:6px}.dsp-control-fit button[data-selected="true"]{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-brand-primary);box-shadow:0 2px 8px var(--dsp-skin-shadow-soft)}.dsp-control-select select{width:100%;height:31px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:0 28px 0 9px;background:var(--dsw-specific-menu);color:var(--dsw-alias-label-primary);color-scheme:inherit;font:inherit;font-size:11px;cursor:pointer;outline:none}.dsp-control-select select:hover{border-color:color-mix(in srgb,var(--dsw-alias-brand-primary) 72%,var(--dsw-alias-border-l2))}.dsp-control-select select:focus-visible{border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary) 22%,transparent)}.dsp-control-select option{background:var(--dsw-specific-menu);color:var(--dsw-alias-label-primary)}.dsp-control-range input{width:100%;height:5px;margin:8px 0 4px;border-radius:999px;accent-color:var(--dsw-alias-brand-primary);cursor:ew-resize}.dsp-control-range input:focus-visible{outline:2px solid color-mix(in srgb,var(--dsw-alias-brand-primary) 68%,transparent);outline-offset:4px}
.dsp-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}
.dsp-card{position:relative;overflow:hidden;display:grid;grid-template-rows:150px minmax(126px,auto);border:1px solid var(--dsw-alias-border-l1);border-radius:15px;background:var(--dsw-alias-bg-layer-1);box-shadow:0 8px 26px var(--dsp-skin-shadow-soft);transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease}
.dsp-card:hover{transform:translateY(-3px);border-color:var(--dsw-alias-border-l2);box-shadow:0 14px 34px var(--dsp-skin-shadow-medium)}.dsp-card[data-active="true"]{border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 1px var(--dsw-alias-brand-primary),0 18px 40px color-mix(in srgb,var(--dsw-alias-brand-primary) 16%,transparent)}
.dsp-preview{position:relative;overflow:hidden;background:var(--dsw-alias-bg-layer-2)}.dsp-preview img{width:100%;height:100%;object-fit:cover;display:block}.dsp-preview-default{display:grid;place-items:center;background:radial-gradient(circle at 70% 30%,color-mix(in srgb,var(--dsw-alias-brand-primary) 20%,transparent),transparent 32%),linear-gradient(145deg,var(--dsw-alias-bg-layer-2),var(--dsw-alias-bg-base))}.dsp-preview-default:before{content:"DSH";font-family:"Baskerville",Georgia,serif;font-size:42px;letter-spacing:.08em;color:var(--dsw-alias-label-primary);opacity:.72}
.dsp-active{position:absolute;top:10px;right:10px;padding:5px 8px;border-radius:20px;background:color-mix(in srgb,var(--dsw-alias-brand-primary) 88%,#000);color:#fff;font-size:10px;font-weight:750;letter-spacing:.08em}
.dsp-card-body{display:flex;flex-direction:column;align-items:flex-start;padding:16px}.dsp-card-meta{display:flex;align-items:center;justify-content:space-between;width:100%;gap:10px}.dsp-card h3{margin:0;font-family:"Baskerville","Iowan Old Style",Georgia,serif;font-size:19px;font-weight:650}.dsp-version{font-size:10px;color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums}.dsp-card p{margin:7px 0 15px;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:1.55}.dsp-card button{margin-top:auto;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:8px 12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;font-weight:700;cursor:pointer;transition:.16s ease}.dsp-card button:hover:not(:disabled){border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}.dsp-card button:disabled{opacity:.48;cursor:default}.dsp-card[data-active="true"] button{background:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);color:#fff}
.dsp-overlay{position:absolute;inset:0;overflow:hidden;pointer-events:none!important;color:var(--dsp-skin-accent)}.dsp-orbit{position:absolute;top:50%;width:260px;height:260px;margin-top:-130px;border:1px solid color-mix(in srgb,var(--dsp-skin-accent) 26%,transparent);border-radius:50%;opacity:.72}.dsp-orbit:before,.dsp-orbit:after{content:"";position:absolute;inset:24px;border:1px dashed color-mix(in srgb,var(--dsp-skin-glow) 28%,transparent);border-radius:50%}.dsp-orbit:after{inset:64px;border-style:solid}.dsp-overlay[data-side="right"] .dsp-orbit{right:-142px}.dsp-overlay[data-side="left"] .dsp-orbit{left:-142px}
.dsp-sigil{position:absolute;bottom:28px;display:grid;grid-template-columns:48px minmax(0,1fr);gap:11px;align-items:center;max-width:240px;padding:10px 14px;border:1px solid color-mix(in srgb,var(--dsp-skin-accent) 40%,transparent);background:color-mix(in srgb,var(--dsw-alias-bg-layer-1) 84%,transparent);backdrop-filter:blur(12px);box-shadow:0 12px 30px var(--dsp-skin-shadow-soft)}.dsp-overlay[data-side="right"] .dsp-sigil{right:28px}.dsp-overlay[data-side="left"] .dsp-sigil{left:28px}.dsp-monogram{display:grid;place-items:center;width:46px;height:46px;border:1px solid currentColor;border-radius:50%;font-family:"Baskerville",Georgia,serif;font-size:14px;font-weight:750;letter-spacing:.08em}.dsp-sigil-copy small{display:block;margin-bottom:3px;font-size:8px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;opacity:.72}.dsp-sigil-copy strong{display:block;font-family:"Baskerville",Georgia,serif;font-size:15px;color:var(--dsw-alias-label-primary)}
body[data-dsh-skin][data-dsh-skin-motion="true"] .dsp-orbit{animation:dsp-rotate 28s linear infinite}body[data-dsh-skin][data-dsh-skin-motion="false"] .dsp-orbit{animation:none}
@keyframes dsp-rotate{to{transform:rotate(360deg)}}
@media(prefers-reduced-motion:reduce){.dsp-card,.dsp-switch input,.dsp-switch input:after,.dsp-orbit{transition:none!important;animation:none!important}}
@media(max-width:900px){.dsp-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dsp-hero{grid-template-columns:1fr}.dsp-count{display:none}.dsp-background{grid-template-columns:240px minmax(0,1fr)}.dsp-background-controls{grid-template-columns:1fr}}
@media(max-width:700px){.dsp-background{grid-template-columns:1fr}.dsp-background-preview{min-height:180px}.dsp-background-preview img{min-height:180px}.dsp-background-body{padding:20px}.dsp-background-heading{align-items:flex-start;flex-direction:column}.dsp-background-actions{justify-content:flex-start}}
@media(max-width:620px){.dsp-grid{grid-template-columns:1fr}.dsp-toolbar{align-items:flex-start;flex-direction:column}.dsp-hero{padding:22px}.dsp-title{font-size:27px}.dsp-sigil{display:none}}
`

/** Install runtime-owned browser styles and remove them with the plugin fiber. */
export function installStyles(ctx: ClientContext): void {
  ctx.effect(() => {
    if (typeof document === 'undefined') return () => {}
    if (document.querySelector(`style[data-plugin-css="${STYLE_ID}"]`) !== null) return () => {}
    const style = document.createElement('style')
    style.dataset.plugin = 'dsh-skin-runtime'
    style.dataset.pluginCss = STYLE_ID
    style.textContent = SKIN_RUNTIME_CSS
    document.head.appendChild(style)
    return () => { style.remove() }
  }, 'skin-runtime: browser styles')
}
